import { isConfigured } from './supabase'

// Demo mode: active whenever Supabase isn't configured (or forced via
// VITE_DEMO=true). Everything runs in-memory with sample data — nothing
// is saved between reloads.
export const demoMode = !isConfigured || import.meta.env.VITE_DEMO === 'true'

const now = new Date().toISOString()
const base = { deleted_at: null, created_at: now, updated_at: now, privacy_level: 'shared', birthday: null, address: '' }

export const demoPeople = [
  {
    ...base,
    id: 'p-elena',
    name: 'Elena Vasquez',
    organization: 'Tucson Compass',
    role: 'Program Director',
    email: 'elena@tucsoncompass.org',
    phone: '(520) 555-0142',
    birthday: '1984-03-14',
    address: '2240 E Broadway Blvd, Tucson, AZ 85719',
    tags: ['Tucson Compass partner'],
    notes: 'Runs the workforce navigation program. Prefers email; responds fast. Interested in a PACE facility tour for her cohort.',
  },
  {
    ...base,
    id: 'p-david',
    name: 'David Chen',
    organization: 'Desert Materials Lab',
    role: 'Metallography Lab Manager',
    email: 'dchen@desertmaterials.com',
    phone: '(520) 555-0177',
    tags: ['PACE customer'],
    notes: 'Bought a grinder/polisher line in 2025. Asks detailed consumables questions — loop in support early.',
  },
  {
    ...base,
    id: 'p-rita',
    name: 'Rita Delgado',
    organization: 'Midtown Neighborhood Association',
    role: 'Board President',
    email: 'rita.delgado@midtownna.org',
    phone: '(520) 555-0118',
    birthday: '1962-11-02',
    tags: ['MNA board'],
    notes: 'Leads the monthly board meeting, first Tuesdays. Strong on zoning issues.',
  },
  {
    ...base,
    id: 'p-sam',
    name: 'Sam Whitfield',
    organization: 'Pima County',
    role: 'Ward 6 Council Aide',
    email: 'sam.whitfield@pima.gov',
    phone: '(520) 555-0163',
    tags: ['Ward 6 contact', 'Pima County'],
    notes: 'Go-to for constituent services and street/lighting requests. Met at the Ward 6 open house.',
  },
  {
    ...base,
    id: 'p-priya',
    name: 'Priya Natarajan',
    organization: 'University of Arizona',
    role: 'Materials Science Professor',
    email: 'priyan@arizona.edu',
    phone: '(520) 555-0190',
    tags: ['PACE customer', 'UA'],
    notes: 'Teaching lab uses PACE equipment. Potential student internship pipeline.',
  },
  {
    ...base,
    id: 'p-tom',
    name: 'Tom Garrity',
    organization: 'Garrity & Sons Machining',
    role: 'Owner',
    email: 'tom@garritymachining.com',
    phone: '(520) 555-0125',
    tags: ['PACE customer'],
    notes: 'Small shop, long-time customer. Calls rather than emails.',
  },
  {
    ...base,
    id: 'p-maria',
    name: 'Maria Fuentes',
    organization: 'Tucson Compass',
    role: 'Volunteer Coordinator',
    email: 'maria@tucsoncompass.org',
    phone: '(520) 555-0151',
    tags: ['Tucson Compass partner'],
    notes: 'Coordinates volunteer events. Best reached Tue–Thu.',
  },
  {
    ...base,
    id: 'p-jack',
    name: 'Jack Osterman',
    organization: 'Midtown Neighborhood Association',
    role: 'Treasurer',
    email: 'jack.o@midtownna.org',
    phone: '(520) 555-0109',
    tags: ['MNA board'],
    notes: 'Handles dues and the annual budget. Retired accountant.',
  },
  {
    ...base,
    id: 'p-lupe',
    name: 'Lupe Ortiz',
    organization: 'Pima County',
    role: 'Economic Development Specialist',
    email: 'lupe.ortiz@pima.gov',
    phone: '(520) 555-0136',
    tags: ['Pima County'],
    notes: 'Point of contact for the small business incentive program.',
  },
  {
    ...base,
    id: 'p-nina',
    name: 'Nina Park',
    organization: '',
    role: 'Neighbor',
    email: '',
    phone: '(520) 555-0171',
    birthday: '1990-07-22',
    address: 'Two doors down — 1314 E 5th St',
    tags: ['Neighbor'],
    privacy_level: 'family_shared',
    notes: 'Two doors down. Has our spare key. Dog: Biscuit.',
  },
]

export const demoOrgs = [
  {
    ...base,
    id: 'o-pace',
    name: 'PACE Technologies',
    type: 'Company',
    description: 'Metallographic equipment and consumables. Home base.',
    key_contacts: [],
    tags: ['work'],
  },
  {
    ...base,
    id: 'o-mna',
    name: 'Midtown Neighborhood Association',
    type: 'Community',
    description: 'Neighborhood association. Board meets first Tuesday of the month.',
    key_contacts: [],
    tags: ['civic'],
  },
  {
    ...base,
    id: 'o-compass',
    name: 'Tucson Compass',
    type: 'Nonprofit',
    description: 'Workforce navigation nonprofit; partnership on facility tours and internships.',
    key_contacts: [],
    tags: ['civic'],
  },
  {
    ...base,
    id: 'o-pima',
    name: 'Pima County',
    type: 'Government',
    description: 'County government contacts — Ward 6 and economic development.',
    key_contacts: [],
    tags: ['civic'],
  },
]

export const demoGroups = [
  {
    id: 'g-pace',
    name: 'PACE Customers',
    all_tags: ['PACE customer'],
    any_tags: [],
    none_tags: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: 'g-civic',
    name: 'Civic Network',
    all_tags: [],
    any_tags: ['MNA board', 'Tucson Compass partner', 'Ward 6 contact', 'Pima County'],
    none_tags: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: 'g-civic-non-gov',
    name: 'Civic — outside government',
    all_tags: [],
    any_tags: ['MNA board', 'Tucson Compass partner'],
    none_tags: ['Pima County'],
    created_at: now,
    updated_at: now,
  },
]

export const demoRelationships = [
  { id: 'r1', person_a_id: 'p-elena', person_b_id: 'p-maria', relationship_type: 'works_with', notes: 'Both at Tucson Compass', created_at: now },
  { id: 'r2', person_a_id: 'p-rita', person_b_id: 'p-jack', relationship_type: 'works_with', notes: 'MNA board', created_at: now },
  { id: 'r3', person_a_id: 'p-sam', person_b_id: 'p-lupe', relationship_type: 'knows', notes: 'Both Pima County', created_at: now },
  { id: 'r4', person_a_id: 'p-david', person_b_id: 'p-priya', relationship_type: 'knows', notes: 'Met at materials conference', created_at: now },
  { id: 'r5', person_a_id: 'p-elena', person_b_id: 'p-rita', relationship_type: 'connected_to', notes: 'Coalition meeting intro', created_at: now },
  { id: 'r6', person_a_id: 'p-sam', person_b_id: 'p-rita', relationship_type: 'knows', notes: 'Ward 6 liaison to MNA', created_at: now },
  { id: 'r7', person_a_id: 'p-tom', person_b_id: 'p-david', relationship_type: 'knows', notes: 'Referred Tom to Desert Materials for testing', created_at: now },
  { id: 'r8', person_a_id: 'p-elena', person_b_id: 'p-lupe', relationship_type: 'connected_to', notes: 'Workforce grant program', created_at: now },
]
